# Generated by Django 4.1.7 on 2023-06-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DB_app', '0007_rename_uesd_referral_code_referralcodes_used_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWebViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('view_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app.customers')),
            ],
        ),
    ]
