# Generated by Django 4.1.7 on 2023-06-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0007_rename_uesd_referral_code_referralcodes_used_referral_code'),
        ('ShopWeb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwebviews',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app.products'),
        ),
    ]
