# Generated by Django 4.1 on 2023-06-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopWeb_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerWebViews',
        ),
    ]
