# Generated by Django 4.1 on 2023-06-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salespeople',
            old_name='username',
            new_name='staff_username',
        ),
    ]
