# Generated by Django 4.1 on 2023-06-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceReservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('Salespeople', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app.salespeople')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app.customers')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app.physicalstores')),
            ],
        ),
    ]
