# Generated by Django 4.1 on 2023-06-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagechairrecord',
            name='experience_questionnaires_fill',
            field=models.BooleanField(default=False),
        ),
    ]
