# Generated by Django 4.1 on 2023-06-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0002_massagechairrecord_experience_questionnaires_fill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencereservations',
            name='Salespeople',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DB_app.salespeople'),
        ),
    ]
