# Generated by Django 4.1 on 2023-06-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0002_experiencereservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencereservations',
            name='reservation_time',
            field=models.DateTimeField(),
        ),
    ]
