# Generated by Django 4.1 on 2023-06-07 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0003_alter_experiencereservations_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecords',
            name='salesperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DB_app.salespeople'),
        ),
    ]
