# Generated by Django 4.1 on 2023-06-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0003_alter_experiencereservations_salespeople'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencereservations',
            old_name='Salespeople',
            new_name='salespeople',
        ),
    ]
