# Generated by Django 4.1 on 2023-06-15 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0004_rename_salespeople_experiencereservations_salespeople'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWebViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app.customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app.products')),
            ],
        ),
        migrations.DeleteModel(
            name='OnlineStoreVisits',
        ),
    ]
