# Generated by Django 4.1.7 on 2023-06-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0005_alter_salesrecords_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcodes',
            name='uesd_referral_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
