# Generated by Django 4.1.7 on 2023-06-12 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0006_alter_referralcodes_uesd_referral_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralcodes',
            old_name='uesd_referral_code',
            new_name='used_referral_code',
        ),
    ]
