# Generated by Django 4.1 on 2023-06-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0006_alter_customers_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecords',
            name='salesperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DB_app.salespeople'),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DB_app.physicalstores'),
        ),
    ]
