# Generated by Django 4.1 on 2023-06-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0007_alter_salesrecords_salesperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquestionnaires',
            name='sales_process_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesquestionnaires',
            name='warranty_process_score',
            field=models.IntegerField(null=True),
        ),
    ]
