# Generated by Django 4.1 on 2023-06-16 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB_app', '0008_alter_salesquestionnaires_sales_process_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerADClicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app.customers')),
            ],
        ),
    ]
